-- Migration stub: version 20260418173456 (fix_drop_duplicate_tables)
-- This migration was applied directly to the Supabase cloud database.
-- This file exists to satisfy Supabase Preview version tracking.
-- No SQL to apply — already executed in production.
