-- Migration stub: version 20260418050819 (fix_handle_new_auth_user_column_names)
-- This migration was applied directly to the Supabase cloud database.
-- This file exists to satisfy Supabase Preview version tracking.
-- No SQL to apply — already executed in production.
