-- Migration stub: version 20260322190000 (draft_rls_core)
-- This migration was applied directly to the Supabase cloud database.
-- This file exists to satisfy Supabase Preview version tracking.
-- No SQL to apply — already executed in production.
