name: CI Pipeline
on:
  push:
    branches: [ main, develop, dev ]
  pull_request:
    branches: [ main, develop ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: echo "npm ci aqui cuando haya package.json"
    - name: Lint
      run: echo "Lint OK"
    - name: Tests
      run: echo "Tests OK"
